### ISSUE TITLE
An error occurs when AddressAutofill is used to query address information by location

### ISSUE THREAD

**Issue by GG-beyond** [mapbox/mapbox-search-ios#118]
let centerCoordinate = CLLocationCoordinate2D(latitude: -34.005676, longitude: 138.795836)//mapView.centerCoordinate
        addressAutofill.suggestions(for: centerCoordinate,with: AddressAutofill.Options()) { [weak self] result in
            guard let self = self else { return }
            switch result {
            case .success(let suggestions):
                if let first = suggestions.first {
                    self.addressAutofill.select(suggestion: first) { [weak self] result in
                        guard let self = self else { return }

                        if case .success = result {
                        } else {
                        }
                    }
                }
            case .failure(let error):
                print("error = \(error)")
            }

error = generic(code: 422, domain: "MapboxCoreSearchErrorDomain", message: "Type \"countryregionpostcodedistrictplacelocalityneighborhoodaddressstreetpoi\" is not a known type. Must be one of: country, region, place, district, locality, postcode, neighborhood, address, poi, poi.landmark")

**Comment by GG-beyond** [comment]
There's another way to do it

`
    func getLocationAddress() {
        engine.reverseGeocoding(options: ReverseGeocodingOptions(point: CLLocationCoordinate2D(latitude: -35.490594, longitude: 138.795836),types: [.address],languages: [])) { [weak self] result in
            guard let self = self else { return}
            switch result {
            case .success(let suggestions):
                print("suggestions = \(suggestions)")
                if let first = suggestions.first {
                    print("first = \(String(describing: first.address))")
                }

            case .failure(let error):
                print("error = \(error)")
            }
        }
    }
`

**Comment by GG-beyond** [comment]
close

**Comment by GG-beyond** [comment]
```
    /// Start searching for query with provided options
    /// - Parameters:
    ///   - coordinate: point Coordinate to resolve
    ///   - options: if no value provided Search Engine will use options from requestOptions field
    final public func suggestions(for coordinate: CLLocationCoordinate2D, with options: MapboxSearch.AddressAutofill.Options? = nil, completion: @escaping (Result<[MapboxSearch.AddressAutofill.Suggestion], Error>) -> Void)
```
Why？

**Comment by kried** [comment]
Hi @GG-beyond 

Thank you for the report. The problem is caused by the [default types](https://github.com/mapbox/mapbox-search-ios/blob/22b12dc8462c453e3e54876acc992d616a76b9c1/Sources/MapboxSearch/PublicAPI/Use%20Cases/Address%20Autofill/AddressAutofill.swift#L155), used in the `AdressAutofill` request.

As a temporary workaround until the fix in the SDK is released, you could use reverse geocoding requests directly on [SearchEngine](https://docs.mapbox.com/ios/search/api/core/1.0.0-rc.4/Classes/SearchEngine.html#/s:12MapboxSearch0B6EngineC16reverseGeocoding7options10completionyAA07ReverseE7OptionsV_ys6ResultOySayAA0bJ0_pGAA0B5ErrorOGctF), without the use of `AdressAutofill`.

**Comment by sarochych** [comment]
Hi @GG-beyond,

We've released a new version of SDK and there is a fix for the issue you reported. Please, check this out.

**Comment by GG-beyond** [comment]
👍🏻
