### ISSUE TITLE
Search box covers Mapbox watermark and info circle button

### ISSUE THREAD

**Issue by William-Coates** [mapbox/mapbox-search-ios#165]
Is it possible to move the Mapbox watermark and info circle button?
![SCR-20240131-kacv](https://github.com/mapbox/mapbox-search-ios/assets/149601233/970405a5-58de-424b-b20e-e84509065c34)

**Comment by aokj4ck** [comment]
@William-Coates according to our [attribution guide](https://docs.mapbox.com/help/getting-started/attribution/) you can use the AttributionButtonOptions to adjust the position.

- v10: https://docs.mapbox.com/ios/maps/api/10.0.1/Structs/AttributionButtonOptions.html
- v11: https://docs.mapbox.com/ios/maps/api/11.1.0/documentation/mapboxmaps/attributionbuttonoptions

I'll look into changes the default behavior for the SearchUI.
