### ISSUE TITLE
ConstantCategoryDataProvider: Minimum number of categories assertion

### ISSUE THREAD

**Issue by linearray** [mapbox/mapbox-search-ios#18]
https://github.com/mapbox/search-ios/blame/main/Sources/MapboxSearchUI/ConstantCategoryDataProvider.swift#L19

`    ///   There is no required minimal number of categories.`

I would argue there is, because if you pass `[]` the assertion a few lines below fails.

Solution: Either change the comment, or allow the behavior of a few versions ago of passing in `[]`.

**Comment by don1ck** [comment]
Will be available in `beta.23`
