### ISSUE TITLE
Xcode Cloud support for version 2.0.0+

### ISSUE THREAD

**Issue by AlfredReisner** [mapbox/mapbox-search-ios#187]
Hello Mapbox Search team,

we are using Xcode Cloud as internal CI pipeline to build the mapbox-search-ios framework 2.0.0-rc.2 setup with SPM.
When building with Xcode 15.3+ we are receiving the follow configuration error:

```
Invalid Bundle. The bundle *.app/Frameworks/MapboxCoreSearch.framework does not support the minimum OS Version specified in the Info.plist.

The bundle 'Payload/*.app/Frameworks/MapboxCoreSearch.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

This bundle Payload/*.app/Frameworks/MapboxCoreSearch.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion
```

Could u please have a look to fix the configuration for us?
If u need any additional information, please reach out to us.

Thanks.

**Comment by aokj4ck** [comment]
Hi @AlfredReisner I'm setting up my own Xcode Cloud environment on a development branch to help triage this issue. Was Xcode Cloud previously working correctly with earlier versions of Xcode or Mapbox SDKs? Can you share your minimum OS version for your project?

**Comment by AlfredReisner** [comment]
Hi, v2.0.0+ still works when we build the pipeline on Xcode 15.2. Only Xcode 15.3+ drops this configuration error.
Our minimum OS version is iOS 16.0. We are also using Mapbox-Maps 11.1.0 and Mapbox-Directions 2.11.1. No issues occur on these SDKs.

**Comment by aokj4ck** [comment]
@AlfredReisner I have a draft pull request available which will update MapboxCoreSearch.framework at https://github.com/mapbox/mapbox-search-ios/pull/196. This version of MapboxCoreSearch is built using Xcode 15.3.

If you wouldn't mind, please try building your app with the MapboxSearch package fetching from branch `SSDK-643-upgrade-search-core-alpha.14` [[link to branch](https://github.com/mapbox/mapbox-search-ios/tree/SSDK-643-upgrade-search-core-alpha.14)].

<img width="879" alt="Screenshot 2024-03-21 at 11 03 44" src="https://github.com/mapbox/mapbox-search-ios/assets/384288/0e9b5fce-a29e-42f6-a458-b9b0cbb261c0">

**Comment by aokj4ck** [comment]
@AlfredReisner and to confirm are you using SPM for your `mapbox-search-ios` dependency, or another system?

**Comment by AlfredReisner** [comment]
@aokj4ck Yes, that is correct.

**Comment by aokj4ck** [comment]
@AlfredReisner please update to our latest release v2.0.3 and let me know if you encounter any issues. https://github.com/mapbox/mapbox-search-ios/releases/tag/v2.0.3

**Comment by AlfredReisner** [comment]
@aokj4ck v2.0.3 solves the issue. 
Thanks a lot!
