### ISSUE TITLE
My token can't find points of interest with the search field api

### ISSUE THREAD

**Issue by abdoul-kader1** [mapbox/mapbox-search-ios#210]
Hello, I use your search field api, in your playground, I can't find the address "ESMA" (school located in the Ivory Coast country), when I fill in my token with a filter for my country, but when I don't enter my token I find the address. Yet with the implementation of the search in my program the token is mandatory I don't know what creates this problem

**Comment by aokj4ck** [comment]
Hi @abdoul-kader1 access to some experimental data sources may not be enabled in your account. Please reach out technical support to enable access to the experimental OSM POI data flag.
