### ISSUE TITLE
Dependency Resolution Failure with mapbox-maps-ios v11.3.0 and mapbox-search-ios v2.0.0

### ISSUE THREAD

**Issue by jeffypooo** [mapbox/mapbox-search-ios#230]
### Xcode Error
```
Failed to resolve dependencies Dependencies could not be resolved because root depends on 'mapbox-maps-ios' 11.3.0 and root depends on 'search-ios' 2.0.0.
'search-ios' is incompatible with 'mapbox-maps-ios' because 'search-ios' 2.0.0 depends on 'mapbox-common-ios' 24.4.0-beta.2..<25.0.0 and 'mapbox-maps-ios' 11.3.0 depends on 'mapbox-common-ios' 24.3.1.
```

**Comment by jeffypooo** [comment]
This also fails with Core v11.2.0 and Search v2.0.0

```
Failed to resolve dependencies Dependencies could not be resolved because root depends on 'mapbox-maps-ios' 11.2.0 and root depends on 'search-ios' 2.0.0.
'search-ios' is incompatible with 'mapbox-maps-ios' because 'search-ios' 2.0.0 depends on 'mapbox-common-ios' 24.4.0-beta.2..<25.0.0 and 'mapbox-maps-ios' 11.2.0 depends on 'mapbox-common-ios' 24.2.0.
```

It would be nice if you folks provided a compatibility matrix for these things

**Comment by jeffypooo** [comment]
### Workaround 
Upgrade core to `v11.4.0-beta.2`. 

This works but I don't like being forced onto a beta version of the core SDK to play nice with a major version release of search.

**Comment by aokj4ck** [comment]
@jeffypooo please update to our latest release v2.0.3 and let me know if you encounter any issues. https://github.com/mapbox/mapbox-search-ios/releases/tag/v2.0.3. Sorry for the confusion, to prevent this issue from occurring again mapbox-search-ios will use an exact version of the MapboxCommon dependency to remain compatible in-step with the other SDKs starting with search v2.0.3.

**Comment by jeffypooo** [comment]
Confirmed fixed ❤️
