### ISSUE TITLE
Invalid PrivacyInfo in v2.0.0 - Unable to submit binary to App Store

### ISSUE THREAD

**Issue by jeffypooo** [mapbox/mapbox-search-ios#233]
Unable to distribute binaries with mapbox-search-ios v2.0.0 due to invalid PrivacyInfo file in `MapboxCoreSearch.framework`

```
TMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/MapboxCoreSearch.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty. Keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.
```

**Comment by jeffypooo** [comment]
This is still present in v2.0.1 @aokj4ck 

This is blocking us from releasing any app updates, please fix

**Comment by jeffypooo** [comment]
We tried adding our own `PrivacyInfo.xcprivacy` file with tracking set to `NO` and still encounter the same problem. Will try setting it to `YES` and see what happens.

**Comment by jeffypooo** [comment]
Setting it to `YES` also does not work

**Comment by jeffypooo** [comment]
Setting to `YES` also does not work.

**Comment by aokj4ck** [comment]
@jeffypooo ah yes sorry about that. I'm working on a new release to fix this starting with our v1 branch and then updating v2 immediately after. Thank you for your patience.

**Comment by jeffypooo** [comment]
@aokj4ck okay sounds good! Thank you!

**Comment by james-wag** [comment]
I'm experiencing a simlar issue with uploading to App Store. 

ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by jeffypooo** [comment]
Just in case it's useful for others, I added a `ci_pre_xcodebuild.sh` script that finds all of the privacy files in `MapboxCoreSearch` and deletes them. This seems to have worked for us re: submission to external beta testers:

```Shell
#!/bin/zsh


DEFAULT_DERIVED_DATA_PATH="${HOME}/Library/Developer/Xcode/DerivedData"

DERIVED_DATA_PATH=${CI_DERIVED_DATA_PATH:-$DEFAULT_DERIVED_DATA_PATH}

echo "Derived data path = ${DERIVED_DATA_PATH}"

# Find all .xcprivacy files in MapboxCoreSearch artifacts and nuke them
privacy_files=($(find $DERIVED_DATA_PATH -type f -path '*/MapboxCoreSearch.xcframework/*.xcprivacy'))
for file in $privacy_files; do
    echo "Deleting $file"
    rm -f ${file}
done
```

**Comment by james-wag** [comment]
When can we expect a patched v1 release? I take it will be (v1.0.2)?

**Comment by jeffypooo** [comment]
@aokj4ck if useful, this tool can scan your project and generate a correct `PrivacyInfo.xcprivacy` file: https://github.com/stelabouras/privacy-manifest

I've used it elsewhere and it works well.

**Comment by aokj4ck** [comment]
@james-wag @jeffypooo I am working on updates for v1 and v2 releases to fix this and I'll keep you posted as soon as these are available.

**Comment by james-wag** [comment]
Hi @aokj4ck , I pulled the latest Mapbox v1.0.2 release branch and ran carthage to populate the `MapboxCoreSearch` and `MapboxCommon` dependencies. However, `MapboxCoreSearch`'s `PrivacyInfo.xcprivacy` file still seems to have the `NSPrivacyTracking` key set to `false`. But the OP's original app store submission error indicates it needs to be set to `true`.

I haven't tried submitting a new app build with v1.0.2 yet, but just wanted to raise this observation.

**Comment by aokj4ck** [comment]
@jeffypooo @james-wag the corrected PrivacyInfo.xcprivacy is available in our latest release v2.0.3, please try that and let me know if you encounter any issues. https://github.com/mapbox/mapbox-search-ios/releases/tag/v2.0.3

**Comment by james-wag** [comment]
@aokj4ck I pulled v2.0.3 and the `MapboxCoreSearch`'s `PrivacyInfo.xcprivacy` file looks good. Will this patch be coming to a v1.0.3 also?

**Comment by aokj4ck** [comment]
@james-wag I have already corrected the PrivacyInfo.xcprivacy in v1.0.2 (using MapboxCoreSearch v1.0.7), https://github.com/mapbox/mapbox-search-ios/releases/tag/v1.0.2 If you're using the v1 series please try this release and let me know if any problems arise.

**Comment by aokj4ck** [comment]
@jeffypooo @james-wag are these problems you encountered solved for you or do you still have MapboxSearch errors?

**Comment by jeffypooo** [comment]
This looks to be fixed now ❤️
