### ISSUE TITLE
Feature Request: Categories/Favorites only viewmode

### ISSUE THREAD

**Issue by don1ck** [mapbox/mapbox-search-ios#27]
Options to hide Favorites and Categories tabs (separately or both):
<img width="252" alt="Screenshot 2022-01-20 at 15 50 29" src="https://user-images.githubusercontent.com/1050454/150341860-55b0dfe1-e2b7-4db2-b10a-6e78df07cbc3.png">

@jvanakker, @linearray anything you would like to add?

**Comment by jvanakker** [comment]
> Options to hide Favorites and Categories tabs (separately or both)

That's it, this would be nice.
