### ISSUE TITLE
Feature Request: SearchBar only mode

### ISSUE THREAD

**Issue by don1ck** [mapbox/mapbox-search-ios#28]
Example: 

![](https://user-images.githubusercontent.com/1019302/143882365-e5b128a5-6de1-4608-8b5d-97cabedee95d.png)

**Comment by don1ck** [comment]
`MapboxPanelController.Configuration` has `bottomOffset` field. Setting it into 90 points will give similar effect. 

<img width="433" alt="Screenshot 2022-01-20 at 16 05 12" src="https://user-images.githubusercontent.com/1050454/150344358-44154ae9-6fe9-4413-ae26-ef448b23ffd2.png">

@linearray is that a desirable "effect" ?

**Comment by kalbaxa** [comment]
closed as stale

**Comment by mattijsdp** [comment]
@don1ck regarding your suggestion to set bottomOffset. How would I do this as configuration is 'inaccesible due to internal protection level'?
