### ISSUE TITLE
Pod built with swift 5.4.2 - Compiler issue 

### ISSUE THREAD

**Issue by velco-greg** [mapbox/mapbox-search-ios#35]
- XCode 13.1
- Macbook M1
- pod 'MapboxSearch', ">= 1.0.0-beta.24", "< 2.0"

I installed MapboxSearch from cocoapods but it seems that it was compiled with an old compiler version :

```
Failed to build module 'MapboxSearch'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)'). Please select a toolchain which matches the SDK.
```

my podfile integrate thoses options :
```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
    config.build_settings['ENABLE_BITCODE'] = 'YES'
    config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = "YES"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
```

I tried downgrade pod version.
I download compiler 5.4.2 but can't build for my device with xcode 13.1 ..

Any ideas ?

Regards

**Comment by velco-greg** [comment]
as mentionned here https://developer.apple.com/forums/thread/687448 
you need to build the lib as XCFramework

**Comment by sarochych** [comment]
Hi @velco-greg,

Search SDK is already distributed as XCFramework, you can easily check it in the Pods/MapboxSearch directory.
I've successfully pulled and compiled Search SDK (beta.24) with Xcode 13.1, device OS version is 
15.3.1.

Could you please provide us with a full sample project with Podfile, so we may dive into your problem?
Thanks in advance!

**Comment by velco-greg** [comment]
Hi @sarochych ,

I resolved the issue. I think it's due to the fact that I was using Mapbox-iOS-SDK (v6)
There is some incompatibility issues between all the versions of pods using MapboxCommon & MapboxMobileEvents..
For now I stop using it, I work on Mapbox v10 update before using it again.

Regards,
Grég
