### ISSUE TITLE
How to modify the text "Where to" of 'search.textfield.placeholder'

### ISSUE THREAD

**Issue by Args** [mapbox/mapbox-search-ios#36]
Is there any way to modify this placeholder?

**Comment by sarochych** [comment]
Hi @Args,
For the moment Search SDK UI is in public beta and has lack of deep customization. 

Btw, we're going to add the opportunity to change search bar placeholder starting from Search UI `beta.26` which will be available, hopefully, today :)

**Comment by kalbaxa** [comment]
Closing now. Feel free to reopen if additional clarifications are required.
