### ISSUE TITLE
SearchUI Language

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-search-ios#40]
I am sure it is already possible somehow, but I am not finding anything in the docu. 

I'd like to localize the SearchUI Strings such as "Gas Station", "Hotel", "Bus station" ect. How or where do I set the UI's Language to the device language?

**Comment by sarochych** [comment]
Hi @JanTG1 ,
For the moment, SearchUI is still in Beta. Unfortunately, we didn’t implement the localization support in our UI module.
 While we don’t have API to provide strings outside the SDK UI module, the only way for now is to fork the repo and provide required localizations on your side.  
 
 That is a known limitation from our side, but we will definitely have such API in final release.

**Comment by sarochych** [comment]
There are two files in SearchUI which can be localized:
- `Categories.strings`
- `Localizable.strings`

In order to support this, you'll need to modify `MapboxSearch.xcodeproj` in your fork and add desired localizations for these files.

Yep, not so convenient as it can be 😅

**Comment by JanTG1** [comment]
@sarochych Thanks for the reply! That does sound like it could be a bit inconvenient, but thanks for pointing out the workaround. I'll have to work with it until that gets released!
