### ISSUE TITLE
no call back Events configuration file [/var/mobile/Containers/Data/Application/0BD436F0-C272-4976-8AF8-9C21685FE38B/Library/Application Support/.mapbox/events_config] doesn't exist

### ISSUE THREAD

**Issue by BMWMWM** [mapbox/mapbox-search-ios#67]
Events configuration file [/var/mobile/Containers/Data/Application/0BD436F0-C272-4976-8AF8-9C21685FE38B/Library/Application Support/.mapbox/events_config] doesn't exist

**Comment by aokj4ck** [comment]
@BMWMWM what version of the SDK were you using when you encountered this error? Is this log warning still occurring on newer versions?
