### ISSUE TITLE
Open source / documentation

### ISSUE THREAD

**Issue by linearray** [mapbox/mapbox-search-ios#8]
From what I gather this downloads a binary from MapBox. Will Search/SearchUI eventually be open-sourced or remain this way?

I tried using it, but the documentation at this point is a bit lacking (I understand it's still in Beta and documentation will improve) and looking at the source doesn't seem to be possible either.

**Comment by kalbaxa** [comment]
Hey @linearray! We are planning to make Search SDK iOS source code public in a week or two. It will be under Mapbox terms of service, though, not open source. I will let you know as it happens.

What are you lacking in the docs right now? Happy to help improving it.

**Comment by linearray** [comment]
Thank you for the quick reply. It's good to hear that we can take a look soon.

I better open a separate issue with my concrete problem, but one thing I noticed that threw me off for quite a bit is this:

The `Configuration` structure entry in the sidebar of the documentation is used for both `MapboxPanelController.Configuration` and `MapboxSearchController.Configuration`, probably because the structs have the same name, and the link will go to one or the other depending on where you came from, which makes it confusing:

https://docs.mapbox.com/ios/search/api/ui/1.0.0-beta.16/Classes/MapboxPanelController/Configuration.html
https://docs.mapbox.com/ios/search/api/ui/1.0.0-beta.16/Structs/Configuration.html

**Comment by kalbaxa** [comment]
@linearray Thanks for noting both cases.

> The `Configuration` structure entry in the sidebar of the documentation is used for both `MapboxPanelController.Configuration` and `MapboxSearchController.Configuration`, probably because the structs have the same name, and the link will go to one or the other depending on where you came from, which makes it confusing:

It is not highlighted correctly in the sidebar though there are 2 different elements for it: one in `Classes` and one in `Structures` - we will fix that if possible with the same name. cc @don1ck 

> MapboxSearchController has a `SearchOptions` structure for `searchOptions` and `categorySearchOptions`, but it is undocumented.

Documentation is in the Core module: https://docs.mapbox.com/ios/search/api/core/1.0.0-beta.17/Structs/SearchOptions.html - I agree it's not obvious, we'll see what we can do here, probably add a cross-link.

**Comment by kalbaxa** [comment]
@linearray happy to announce, we are public code now.
